config/routes.rb
Rails.application.routes.draw do
  get '/welcome', to: 'welcome#index'

  get '/pdv', to: 'pdv#index'
  get 'pdv/get_products', to: 'pdv#get_products'
  post 'pdv/create_order', to: 'pdv#create_order'
  get 'order_items/list_items', to:'order_items#list_items'

  root 'welcome#index'
  
  resources :expenses
  resources :expense_kinds
  resources :payment_methods
  resources :requests
  resources :order_items
  resources :orders
  resources :customers
  resources :products
  resources :origins

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/models/expense_kind.rb
class ExpenseKind < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :customer
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/origin.rb
class Origin < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :customer
end

app/controllers/origins_controller.rb
class OriginsController < ApplicationController
  before_action :set_origin, only: [:show, :edit, :update, :destroy]

  # GET /origins
  # GET /origins.json
  def index
    @origins = Origin.all
  end

  # GET /origins/1
  # GET /origins/1.json
  def show
  end

  # GET /origins/new
  def new
    @origin = Origin.new
  end

  # GET /origins/1/edit
  def edit
  end

  # POST /origins
  # POST /origins.json
  def create
    @origin = Origin.new(origin_params)

    respond_to do |format|
      if @origin.save
        format.html { redirect_to @origin, notice: 'Origin was successfully created.' }
        format.json { render :show, status: :created, location: @origin }
      else
        format.html { render :new }
        format.json { render json: @origin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /origins/1
  # PATCH/PUT /origins/1.json
  def update
    respond_to do |format|
      if @origin.update(origin_params)
        format.html { redirect_to @origin, notice: 'Origin was successfully updated.' }
        format.json { render :show, status: :ok, location: @origin }
      else
        format.html { render :edit }
        format.json { render json: @origin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /origins/1
  # DELETE /origins/1.json
  def destroy
    @origin.destroy
    respond_to do |format|
      format.html { redirect_to origins_url, notice: 'Origin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_origin
      @origin = Origin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def origin_params
      params.require(:origin).permit(:name)
    end
end

app/controllers/pdv_controller.rb
class PdvController < ApplicationController
  protect_from_forgery with: :null_session
  def index
    @customers = Customer.select(:id, :name).order(:name).map { |e| [e.name, e.id]}
    @origins = Origin.select(:id, :name).order(:name).map { |e| [e.name, e.id]}
    @products = Product.select(:nome, :id).order(:nome).map { |e| [e.nome, e.id]}
  end

  def get_products
    @product = Product.find(params['product_id'])
    render :get_items
  end

  def create_order
    order = Order.create(order_params)
    order_items_params.each do |e|
      e[:order_id] = order.id
      OrderItem.create(e)
    end
  end

  private
  def order_params
    params.require(:order).permit(:customer_id, :value, :payment, :origin, :request_ahead)
  end

  def order_items_params
    params.require('order_items').map do |e|
      e.permit(:product_id, :quantity, :value)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/expense_kinds_helper.rb
module ExpenseKindsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/origins_helper.rb
module OriginsHelper
end

app/helpers/pdv_helper.rb
module PdvHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/origins/_form.html.erb
<%= form_with(model: origin, local: true) do |form| %>
  <% if origin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(origin.errors.count, "error") %> prohibited this origin from being saved:</h2>

      <ul>
        <% origin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Origem' %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.button '<i class="material-icons right">save</i>Salvar'.html_safe, class: "blue-grey btn waves-effect waves-light" %>
  </div>
<% end %>

app/views/origins/edit.html.erb
<h1>Editar Origem de Venda</h1>

<%= render 'form', origin: @origin %>
<br>
<%= link_to 'Mostrar', @origin, class: "blue-grey btn waves-effect waves-light"  %>
<%= link_to 'Voltar', origins_path, class: "blue-grey btn waves-effect waves-light"  %>

app/views/origins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Origens de Venda</h1>

<br>
<%= link_to '<i class="material-icons left">money</i>Nova Origem'.html_safe, 
            new_origin_path, 
            class: "blue-grey btn waves-effect waves-light" %>

<table>
  <thead>
    <tr>
      <th>Origem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @origins.each do |origin| %>
      <tr>
        <td><%= origin.name %></td>
        <td><%= link_to 'Mostrar', origin %></td>
        <td><%= link_to 'Editar', edit_origin_path(origin) %></td>
        <td><%= link_to 'Apagar', origin, method: :delete, data: { confirm: 'Tem certeza de que deseja apagar o registro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/origins/new.html.erb
<h1>Nova Origem de Venda</h1>

<%= render 'form', origin: @origin %>
<br>
<%= link_to 'Voltar', origins_path, class: "blue-grey btn waves-effect waves-light" %>

app/views/origins/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Origem de Venda</h1>
<p>
  <strong>Origem:</strong>
  <%= @origin.name %>
</p>

<%= link_to 'Editar', edit_origin_path(@origin), class: "blue-grey btn waves-effect waves-light" %>
<%= link_to 'Voltar', origins_path, class: "blue-grey btn waves-effect waves-light" %>