config/routes.rb
Rails.application.routes.draw do
  get '/welcome', to: 'welcome#index'

  get '/pdv', to: 'pdv#index'
  get 'pdv/get_products', to: 'pdv#get_products'
  post 'pdv/create_order', to: 'pdv#create_order'
  get 'order_items/list_items', to:'order_items#list_items'

  root 'welcome#index'
  
  resources :expenses
  resources :expense_kinds
  resources :payment_methods
  resources :requests
  resources :order_items
  resources :orders
  resources :customers
  resources :products
  resources :origins

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/models/expense_kind.rb
class ExpenseKind < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :customer
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/origin.rb
class Origin < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :customer
end

app/controllers/pdv_controller.rb
class PdvController < ApplicationController
  protect_from_forgery with: :null_session
  def index
    @customers = Customer.select(:id, :name).order(:name).map { |e| [e.name, e.id]}
    @origins = Origin.select(:id, :name).order(:name).map { |e| [e.name, e.id]}
    @products = Product.select(:nome, :id).order(:nome).map { |e| [e.nome, e.id]}
  end

  def get_products
    @product = Product.find(params['product_id'])
    render :get_items
  end

  def create_order
    order = Order.create(order_params)
    order_items_params.each do |e|
      e[:order_id] = order.id
      OrderItem.create(e)
    end
  end

  private
  def order_params
    params.require(:order).permit(:customer_id, :value, :payment, :origin, :request_ahead)
  end

  def order_items_params
    params.require('order_items').map do |e|
      e.permit(:product_id, :quantity, :value)
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.where("delivery_date >= '#{Date.today}'")
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    byebug
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Encomenda criada com sucesso!.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Encomenda editada com sucesso!.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Encomenda apagada com sucesso!.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:customer_id, :delivery, :items, :delivery_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/expense_kinds_helper.rb
module ExpenseKindsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/origins_helper.rb
module OriginsHelper
end

app/helpers/pdv_helper.rb
module PdvHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/requests/_form.html.erb
<%= form_with(model: request, local: true) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>
      <ul>
        <% request.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <div class="input_field">
      <%= form.label :cliente%>
      <%= form.select :customer_id, 
      options_for_select(Customer.select(:name, :id).map { |e| [e.name, e.id]}) %>
    </div>
  </div>
  <div class="input_field">
    <label for="request_delivery">
      <input name="request[delivery]" type="hidden" value="0">
      <input type="checkbox" value="1" name="request[delivery]" id="request_delivery" <%= request.delivery ? "checked" : "" %>>
      <span>Para entrega</span>
    </label>
  </div>
  <div class="input_field">
    <%= form.label :items %>
    <%= form.text_area :items, class: "materialize-textarea" %>
  </div>
  <div class="row">
    <div class="padz input_field col s3">
      <%= form.label :delivery_date, 'Data de Entrega' %>
      <%= form.text_field :delivery_date, class:'datepicker' %>
    </div>
  </div>
  <div class="actions">
    <%= form.button '<i class="material-icons right">save</i>Salvar'.html_safe, class: "blue-grey btn waves-effect waves-light" %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editar Encomenda</h1>

<%= render 'form', request: @request %>
<br>
<%= link_to 'Exibir', @request, class: "blue-grey btn waves-effect waves-light" %> 
<%= link_to 'Voltar', requests_path, class: "blue-grey btn waves-effect waves-light" %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Encomendas</h1>
<%= link_to '<i class="material-icons left">assignment</i>Nova encomenda'.html_safe, 
            new_request_path, 
            class: 'blue-grey btn waves-effect waves-light' %>
<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Delivery</th>
      <th>Itens</th>
      <th>Data de Entrega</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.customer_id %></td>
        <td><%= request.delivery %></td>
        <td class="pre-line"><%= request.items %></td>
        <td><%= request.delivery_date %></td>
        <td><%= link_to 'Exibir', request %></td>
        <td><%= link_to 'Editar', edit_request_path(request) %></td>
        <td><%= link_to 'Apagar', request, method: :delete, data: { confirm: 'Tem certeza de que deseja apagar o registro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/requests/new.html.erb
<h1>Nova Encomenda</h1>

<%= render 'form', request: @request %>
<br>
<%= link_to 'Voltar', requests_path, class: "blue-grey btn waves-effect waves-light" %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Informações da Encomenda</h1>
<p>
  <strong>Cliente:</strong>
  <%= link_to customer_path(@request.customer) do %>
    <%= @request.customer.name %>
  <% end %>
</p>

<p>
  <strong>Delivery:</strong>
  <%= @request.delivery %>
</p>

<p class='pre-line neg-margin15'>
  <strong>Itens:</strong>
  <%= @request.items %>
</p>

<p>
  <strong>Data de entrega:</strong>
  <%= @request.delivery_date %>
</p>

<%= link_to 'Editar', edit_request_path(@request), class: "blue-grey btn waves-effect waves-light" %> 
<%= link_to 'Voltar', requests_path, class: "blue-grey btn waves-effect waves-light" %>