config/routes.rb
Rails.application.routes.draw do
  get '/welcome', to: 'welcome#index'

  get '/pdv', to: 'pdv#index'
  get 'pdv/get_products', to: 'pdv#get_products'
  post 'pdv/create_order', to: 'pdv#create_order'
  get 'order_items/list_items', to:'order_items#list_items'

  root 'welcome#index'
  
  resources :expenses
  resources :expense_kinds
  resources :payment_methods
  resources :requests
  resources :order_items
  resources :orders
  resources :customers
  resources :products
  resources :origins

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/models/expense_kind.rb
class ExpenseKind < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :customer
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/origin.rb
class Origin < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :customer
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where("created_at >= ?", Date.today)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:customer_id, :value, :value, :discount, :discount, :payment, :origin, :request_ahead)
    end
end

app/controllers/pdv_controller.rb
class PdvController < ApplicationController
  protect_from_forgery with: :null_session
  def index
    @customers = Customer.select(:id, :name).order(:name).map { |e| [e.name, e.id]}
    @origins = Origin.select(:id, :name).order(:name).map { |e| [e.name, e.id]}
    @products = Product.select(:nome, :id).order(:nome).map { |e| [e.nome, e.id]}
  end

  def get_products
    @product = Product.find(params['product_id'])
    render :get_items
  end

  def create_order
    order = Order.create(order_params)
    order_items_params.each do |e|
      e[:order_id] = order.id
      OrderItem.create(e)
    end
  end

  private
  def order_params
    params.require(:order).permit(:customer_id, :value, :payment, :origin, :request_ahead)
  end

  def order_items_params
    params.require('order_items').map do |e|
      e.permit(:product_id, :quantity, :value)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/expense_kinds_helper.rb
module ExpenseKindsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/origins_helper.rb
module OriginsHelper
end

app/helpers/pdv_helper.rb
module PdvHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.text_field :discount %>
  </div>

  <div class="field">
    <%= form.label :payment %>
    <%= form.text_field :payment %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin %>
  </div>

  <div class="field">
    <%= form.label :request_ahead %>
    <%= form.check_box :request_ahead %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendas</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Valor</th>
      <th>Tipo de Pagamento</th>
      <th>Origem</th>
      <th>Encomenda</th>
      <th>Itens</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
    <tr>
      <td><%= link_to customer_path(order.customer_id) do%>
        <%= order.customer.name %>
        <% end %>
      </td>
      <td><%= "R$ %0.2f" % [order.value] %></td>
      <td><%= order.payment %></td>
      <td><%= order.origin %></td>
      <td><%= order.request_ahead ? 'Sim' : 'Não'%></td>
      <td><%= link_to 'Abrir', order_items_list_items_path(id: order.id) %></td>
      <td><%= link_to 'Exibir', order_path(order.id) %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td>
        <h5>Total</h5>
      </td>
      <td>
        <h5><%= "R$ %0.2f" % [@orders.reduce(0) { |sum, e| sum += e.value }] %></h5>
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tfoot>
</table>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @order.value %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @order.discount %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @order.payment %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @order.origin %>
</p>

<p>
  <strong>Request ahead:</strong>
  <%= @order.request_ahead %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>