config/routes.rb
Rails.application.routes.draw do
  get '/welcome', to: 'welcome#index'

  get '/pdv', to: 'pdv#index'
  get 'pdv/get_products', to: 'pdv#get_products'
  post 'pdv/create_order', to: 'pdv#create_order'
  get 'order_items/list_items', to:'order_items#list_items'

  root 'welcome#index'
  
  resources :expenses
  resources :expense_kinds
  resources :payment_methods
  resources :requests
  resources :order_items
  resources :orders
  resources :customers
  resources :products
  resources :origins

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/models/expense_kind.rb
class ExpenseKind < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :customer
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/origin.rb
class Origin < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :customer
end

app/controllers/pdv_controller.rb
class PdvController < ApplicationController
  protect_from_forgery with: :null_session
  def index
    @customers = Customer.select(:id, :name).order(:name).map { |e| [e.name, e.id]}
    @origins = Origin.select(:id, :name).order(:name).map { |e| [e.name, e.id]}
    @products = Product.select(:nome, :id).order(:nome).map { |e| [e.nome, e.id]}
  end

  def get_products
    @product = Product.find(params['product_id'])
    render :get_items
  end

  def create_order
    order = Order.create(order_params)
    order_items_params.each do |e|
      e[:order_id] = order.id
      OrderItem.create(e)
    end
  end

  private
  def order_params
    params.require(:order).permit(:customer_id, :value, :payment, :origin, :request_ahead)
  end

  def order_items_params
    params.require('order_items').map do |e|
      e.permit(:product_id, :quantity, :value)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Produto criado com sucesso!' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Produto editado com sucesso!' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Produto apagado com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:nome, :tipo, :preco)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/expense_kinds_helper.rb
module ExpenseKindsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/origins_helper.rb
module OriginsHelper
end

app/helpers/pdv_helper.rb
module PdvHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/products/_form.html.erb
<% content_for(:disable_turbolinks) { 'no-cache' } %>
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="input-field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="input-field">
    <%= form.label :preco, 'Preço' %>
    <%= form.text_field :preco, placeholder: 'R$' %>
  </div>

  <div class="actions">
    <%= form.button '<i class="material-icons right">save</i>Salvar'.html_safe, class: "blue-grey btn waves-effect waves-light" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form', product: @product %>
<br>
<%= link_to 'Exibir', @product, class: "blue-grey btn waves-effect waves-light" %>
<%= link_to 'Voltar', products_path, class: "blue-grey btn waves-effect waves-light" %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>
<%= link_to '<i class="material-icons left">cake</i>Novo produto'.html_safe, 
            new_product_path, 
            class: 'blue-grey btn waves-effect waves-light' %>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Tipo</th>
      <th>Preço</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.nome %></td>
        <td><%= product.tipo %></td>
        <td><%= "R$ %0.2f" % [product.preco] %></td>
        <td><%= link_to 'Exibir', product %></td>
        <td><%= link_to 'Editar', edit_product_path(product) %></td>
        <td><%= link_to 'Destruir', product, method: :delete, data: { confirm: 'Tem certeza que deseja destruir o registro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Voltar', welcome_path, class: "blue-grey btn waves-effect waves-light" %>

app/views/products/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form', product: @product %>
<br>
<%= link_to 'Voltar', products_path, class: "blue-grey btn waves-effect waves-light" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Descrição do Produto</h1>
<p>
  <strong>Nome:</strong>
  <%= @product.nome %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @product.tipo %>
</p>

<p>
  <strong>Preço:</strong>
  <%= "R$ %0.2f" % [@product.preco] %>
</p>

<%= link_to 'Editar', edit_product_path(@product), class: "blue-grey btn waves-effect waves-light" %>
<%= link_to 'Voltar', products_path, class: "blue-grey btn waves-effect waves-light" %>